development:
  adapter: postgresql
  database: imkven_feed_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: imkven_feed_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: imkven_feed_production
  pool: 5
  timeout: 5000
